apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-mysql-pvc
  labels:
    app: ecommerce-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
